# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('link', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to=projects.models.upload_image_path)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
