# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-14 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_page',
        ),
    ]
