# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import mainPage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('career', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('photo', models.FileField(null=True, upload_to=mainPage.models.upload_image_path)),
            ],
        ),
    ]
