# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-06 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_auto_20190306_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_data',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
