# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0003_info_data_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_data',
            name='mobile',
            field=models.CharField(max_length=23),
        ),
    ]
