# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-08 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0004_auto_20190308_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info_data',
            name='slug',
        ),
    ]
