# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190309_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='interests',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cv',
            name='tech_train',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
