# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20190309_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='interests',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
