# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20190309_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_train', models.CharField(blank=True, max_length=500)),
                ('skills', models.CharField(blank=True, max_length=100)),
                ('interests', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='interest',
        ),
        migrations.DeleteModel(
            name='skill',
        ),
        migrations.DeleteModel(
            name='tech_train',
        ),
    ]
