# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-10 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20190310_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_train', models.CharField(blank=True, max_length=500)),
                ('skills', models.CharField(blank=True, max_length=100)),
                ('interests', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='interest',
        ),
        migrations.DeleteModel(
            name='skill',
        ),
        migrations.DeleteModel(
            name='train',
        ),
    ]
