# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20190313_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='myresume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.FileField(null=True, upload_to=resume.models.upload_file_path)),
            ],
        ),
    ]
