# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-22 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_myresume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myresume',
            name='link',
        ),
        migrations.AddField(
            model_name='myresume',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='upload_file_path'),
            preserve_default=False,
        ),
    ]
